### ISSUE TITLE
Solution for Heroku Suspension.

### ISSUE THREAD

**Issue by pushpa-raj-thazhathillada** [TOXIC-DEVIL/Leon#37]
Please solve the issue that suspend the heroku account when I deploy bot.

**Comment by TOXIC-DEVIL** [comment]
> Please solve the issue that suspend the heroku account when I deploy bot.

Hi @pushpa-raj-thazhathillada !
I can't do any fix with this coz its fault of heroku and not mine. But I'm still working to fix that. Soon I will be uploading a solution in our [YouTube Channel](https://youtube.com/c/TOXIC-DEVIL-YT). Stay tuned for that video. Thank You for this issue! 💖

**Comment by pushpa-raj-thazhathillada** [comment]
> > Please solve the issue that suspend the heroku account when I deploy bot.
> 
> Hi @pushpa-raj-thazhathillada ! I can't do any fix with this coz its fault of heroku and not mine. But I'm still working to fix that. Soon I will be uploading a solution in our [YouTube Channel](https://youtube.com/c/TOXIC-DEVIL-YT). Also this may help you: #31 . Stay tuned for that video. Thank You for this issue! 💖

Ok, But when will you upload video, Atleast estimated time?

**Comment by TOXIC-DEVIL** [comment]
> > > Please solve the issue that suspend the heroku account when I deploy bot.
> > 
> > 
> > Hi @pushpa-raj-thazhathillada ! I can't do any fix with this coz its fault of heroku and not mine. But I'm still working to fix that. Soon I will be uploading a solution in our [YouTube Channel](https://youtube.com/c/TOXIC-DEVIL-YT). Also this may help you: #31 . Stay tuned for that video. Thank You for this issue! 💖
> 
> Ok, But when will you upload video, Atleast estimated time?

Estimated in 2 weeks. I'll be informing here when I upload it.

**Comment by pushpa-raj-thazhathillada** [comment]
> > > > Please solve the issue that suspend the heroku account when I deploy bot.
> > > 
> > > 
> > > Hi @pushpa-raj-thazhathillada ! I can't do any fix with this coz its fault of heroku and not mine. But I'm still working to fix that. Soon I will be uploading a solution in our [YouTube Channel](https://youtube.com/c/TOXIC-DEVIL-YT). Also this may help you: #31 . Stay tuned for that video. Thank You for this issue! 💖
> > 
> > 
> > Ok, But when will you upload video, Atleast estimated time?
> 
> Estimated in 2 weeks. I'll be informing here when I upload it.

Ok tanks

**Comment by TOXIC-DEVIL** [comment]
We have fixed the issue by finding a new website for deploying Leon. Thank You for informing us! You can now checkout the [video ( Leon Installation ) [ SUSPENSION FIXED ]](https://youtu.be/tiOHHhOgNJs).
Thanks Again!

**Comment by pushpa-raj-thazhathillada** [comment]
> We have fixed the issue by finding a new website for deploying Leon. Thank You for informing us! You can now checkout the [video ( Leon Installation ) [ SUSPENSION FIXED ]](https://youtu.be/tiOHHhOgNJs). Thanks Again!

You are awesome brooh! 😍
