### ISSUE TITLE
Generating Auth Id

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [toxic-devil/Leon#5]
How do I generate Auth id and get cred.json?

**Comment by toxic-devil** [comment]
> How do I generate Auth id and get cred.json?

You can go [here](https://github.com/TOXIC-DEVIL/Leon?tab=readme-ov-file#auth) and click 'Authenticate with WhatsApp' button. Scan the displayed qr code and you'll get the AUTH_ID in your WhatsApp.
